config/routes.rb
Rails.application.routes.draw do
  resources :guidelines

end

app/models/guideline.rb
class Guideline < ActiveRecord::Base
  # Relations to releases
  has_many :releases
  # For nested attributes
  accepts_nested_attributes_for :releases, :reject_if => :all_blank, :allow_destroy => true
end

app/models/release.rb
class Release < ActiveRecord::Base
  belongs_to :guideline
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guidelines_controller.rb
class GuidelinesController < ApplicationController
  before_action :set_guideline, only: [:show, :edit, :update, :destroy]

  # GET /guidelines
  # GET /guidelines.json
  def index
    @guidelines = Guideline.all
    @guidelines_grid = initialize_grid(Guideline)
  end

  # GET /guidelines/1
  # GET /guidelines/1.json
  def show
  end

  # GET /guidelines/new
  def new
    @guideline = Guideline.new
  end

  # GET /guidelines/1/edit
  def edit
  end

  # POST /guidelines
  # POST /guidelines.json
  def create
    @guideline = Guideline.new(guideline_params)

    respond_to do |format|
      if @guideline.save
        format.html { redirect_to @guideline, notice: 'Guideline was successfully created.' }
        format.json { render :show, status: :created, location: @guideline }
      else
        format.html { render :new }
        format.json { render json: @guideline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guidelines/1
  # PATCH/PUT /guidelines/1.json
  def update
    respond_to do |format|
      if @guideline.update(guideline_params)
        format.html { redirect_to @guideline, notice: 'Guideline was successfully updated.' }
        format.json { render :show, status: :ok, location: @guideline }
      else
        format.html { render :edit }
        format.json { render json: @guideline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guidelines/1
  # DELETE /guidelines/1.json
  def destroy
    @guideline.destroy
    respond_to do |format|
      format.html { redirect_to guidelines_url, notice: 'Guideline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guideline
      @guideline = Guideline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guideline_params
      params.require(:guideline).permit(:name, :description, releases_attributes: [:id, :name, :done, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guidelines_helper.rb
module GuidelinesHelper
end

app/views/guidelines/_form.html.erb
<%= form_for(@guideline) do |f| %>
  <% if @guideline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guideline.errors.count, "error") %> prohibited this guideline from being saved:</h2>

      <ul>
      <% @guideline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.fields_for :releases do |release| %><br>
    <!-- Render the partial with the releases attributes -->
    <%= render 'release_fields', :f => release %>
    <% end %>
    <div class="links">
    	<!-- Link that shows up dinamicly the releases fields -->
	    <%= link_to_add_association 'add release', f, :releases %><br>
	</div>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guidelines/_grid.html.erb
<%# show_filters: :when_filtered %>
<%= grid(@guidelines_grid) do |g|

  g.column  name:  'Name', attribute: 'name' do |guide|
    guide.name
  end

  g.column   do |guide|
    link_to('Edit', edit_guideline_path(guide))
  end
end -%>

app/views/guidelines/_release_fields.html.erb
<!-- Partial with the nested form -->
<div class="nesated-fields">
	
	<div class="field">
	<%= f.label :release_date %><br>
	<%= f.text_field :release_date %>
	</div>
	
	<div class="field">
	<%= f.check_box :done %><br>
	<%= f.label :done %>
	</div>
	<!-- Link that dinamicly removes the relaeses fields -->
	<%= link_to_remove_association "remove task", f %>
	
</div>

app/views/guidelines/edit.html.erb
<h1>Editing guideline</h1>

<%= render 'form' %>

<%= link_to 'Show', @guideline %> |
<%= link_to 'Back', guidelines_path %>

app/views/guidelines/index.html.erb
<h1>Listing guidelines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guidelines.each do |guideline| %>
      <tr>
        <td><%= guideline.name %></td>
        <td><%= link_to 'Show', guideline %></td>
        <td><%= link_to 'Edit', edit_guideline_path(guideline) %></td>
        <td><%= link_to 'Destroy', guideline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'grid'%>

<br>

<%= link_to 'New Guideline', new_guideline_path %>

app/views/guidelines/new.html.erb
<h1>New guideline</h1>

<%= render 'form' %>

<%= link_to 'Back', guidelines_path %>

app/views/guidelines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guideline.name %>
</p>

<%= link_to 'Edit', edit_guideline_path(@guideline) %> |
<%= link_to 'Back', guidelines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guidelines</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>